name: Deploy Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Navigate to the correct directory and install dependencies
    - name: Install dependencies
      run: |
        cd mern-todo-app/client
        npm install

    # Build the application
    - name: Build the application
      run: |
        cd mern-todo-app/client
        npm run build

    # Deploy to your hosting service (e.g., Vercel/Netlify)
    - name: Deploy to Vercel
      run: |
        cd mern-todo-app/client
        npx vercel --prod --yes
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
